export class GetMobilityRequestByIdQuery {
  id: number;
  address: string;
  area: string;
  arrivalKM: string;
  arrivalTime: string;
  brand: string;
  color: string;
  commissionedStaff: string;
  departureKM: string;
  departureTime: string;
  district: string;
  documentsUrl: string;
  driver: any;
  engineNumber: string;
  entity: string;
  licensePlate: string;
  model: string;
  objective: string;
  observation: string;
  serialNumber: string;
  serviceDate: Date;
  serviceHour: Date;
  serviceNumber: string;
  type: string;
  userArea: string;
  year: string;
  registrationState: boolean;
}
